# Generated by Django 4.1.7 on 2023-03-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raspberry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLugar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionMCA', models.CharField(max_length=200)),
                ('idLugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspberry.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutTrabajador', models.CharField(max_length=200)),
                ('sentido', models.IntegerField()),
                ('fechaHora', models.CharField(max_length=200)),
                ('dirFoto', models.CharField(max_length=200)),
                ('idMCA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspberry.mca')),
            ],
        ),
    ]
